#????
server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&charactorEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
    oracleucp:
      port-number: 3306
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html



# mybatis-spring-boot-starter  当使用的依赖是springboot包时，不需要此类配置

#mybatis:
#  mapper-locations: classpath:com/xss/test/mapper/*.xml
#  type-aliases-package: com.xss.test
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

